name: Multi-K8s CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  # ==========================================================
  # CI - PROBAR EL CLIENTE
  # ==========================================================
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Construir imagen de pruebas del cliente
        run: docker build -t multi-client-test -f ./client/Dockerfile.dev ./client

      - name: Ejecutar tests del cliente
        run: docker run -e CI=true multi-client-test npm test -- --watchAll=false


  # ==========================================================
  # BUILD Y PUSH - SOLO CUANDO LLEGAMOS A MAIN
  # ==========================================================
  build-and-push:
    needs: test

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir imágenes Docker
        run: |
          docker build \
            -t gabomur/multi-client:latest \
            -t gabomur/multi-client:${{ github.sha }} \
            ./client

          docker build \
            -t gabomur/multi-server:latest \
            -t gabomur/multi-server:${{ github.sha }} \
            ./server

          docker build \
            -t gabomur/multi-worker:latest \
            -t gabomur/multi-worker:${{ github.sha }} \
            ./worker

      - name: Subir imágenes a Docker Hub
        run: |
          docker push gabomur/multi-client:latest
          docker push gabomur/multi-client:${{ github.sha }}

          docker push gabomur/multi-server:latest
          docker push gabomur/multi-server:${{ github.sha }}

          docker push gabomur/multi-worker:latest
          docker push gabomur/multi-worker:${{ github.sha }}